### ISSUE TITLE
is the plugin need WearOS for work Correctly?

### ISSUE THREAD

**Issue by ImanGhasemiArani** [Rexios80/wear_plus#1]
hello, 
We have already had a conversation about other issues in the waer plugin repo.

in this case I guess the OS of watch isn't a WearOS.
I got the android version in watch that return Android version 8.1.0.
have can I detect that use WearOS or pure Android?

**Comment by ImanGhasemiArani** [comment]
@Rexios80 
Hi,
How can I root the android watch ? Or flash that, then install WearOS or my custom android?
Can you help ?

**Comment by Rexios80** [comment]
This plugin allows the use of Wear OS APIs in a Flutter application. If the device does not run Wear OS, then that is out of the support scope for this plugin.

**Comment by ImanGhasemiArani** [comment]
> This plugin allows the use of Wear OS APIs in a Flutter application. If the device does not run Wear OS, then that is out of the support scope for this plugin. 

Ok. Thanks. 
Can you tell me how to root an android smart watch? Or even flash and  install WearOS on it?

**Comment by Rexios80** [comment]
No
